language: node_js
node_js:
- 9
- 8
- 7
- 6
before_install:
- npm install -g npm@latest
before_deploy:
  - cd api
  - npm install -g babel-cli
deploy:
  provider: npm
  email: alf.g.jr@gmail.com
  api_key:
    secure: hMUs/olGsP8M419ALhmoSGNpfZUOWyDXcyHfD4mdkppBOTQBBGCUeLRKdMWbmsGMVU54eFteEiXSr9VFUJZduXwoEXNQPe0ep1Y5Vo1jCCYoiR+7TAQ+oa9+dxAS7d7UmLrTIgXypR1jaIA7EyB+F1uellyGlR1ngab0ZCK/Q29vpsXEL6A7XRjkMp8RLZpeTYqbG4PuROETjBJenZ0GT2oBoN8TZ9Eq2mEyH0AEnSBKzeOFcLVcrYfOgreVWygxHnYvJmfimw2jjx8PYQkeU1n/bwpXyNEPtBpnfObvmkAFqD3eQsYRXnZYHfLC5zD7BZu+LUTu4HvJCNuCDvK2uxcyVgO/4lJB1jM4rrEmdC408/WzpiEn1Go8DfPtAM4o/KEWMuNFNLNqNENGnB620xPjU4pU+d2OhH7kO7/ziQ8k5F4/vqWoT1QaCRF6aPFiM9KlX5p1mNk0LTFe5Lr2NlshlIH18V6eyb2oxTirxiOer9UQaTcFfKLcq2WCad5u7sV6fqYSCIMX98N8Q2h4dyiJ4SM3tlUQ8MWNkDClmFEb5LLEZ/eL86DAKbL5PkM6fazf/4glRg9StFrflp7ujyKGZsWv3IUUfftWUi+59jxXTsKM9cyI36fl43xswQzB15TPl0GVH4LGNacH9boDVzOCKE2q8lpPD9fx4tN2d5A=
  on:
    tags: true
    repo: alfg/overwatch-api
